traininglog/weight/forms.py
# weight/forms.py
# Jake Malley
# 03/02/15

"""
Defines the forms used in the weight blueprint.
"""

# Imports
from flask_wtf import Form
from wtforms import DecimalField
from wtforms.validators import DataRequired, NumberRange

class AddWeightForm(Form):

    """
    Form for users to add weight.
    """

    # Decimal field for the weight.
    weight = DecimalField('weight', validators=[DataRequired(), NumberRange(min=0,max=200)])

traininglog/__init__.py
# __init__.py
# Jake Malley
# 15/01/2015

"""
Tells python to treat this directory as a package.
Creates the flask app. 
"""

# Imports
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.bcrypt import Bcrypt
from flask.ext.login import LoginManager
from os import environ

# Create the flask app.
app = Flask(__name__)
# Create a bcrypt object for password hashing.
bcrypt = Bcrypt(app)

# Get the configuration class to use from a environment variable.
try:
    # Load the configuration class specified in the environment variable
    # 'TRAINING_LOG_CONFIG'
    app.config.from_object(environ['TRAINING_LOG_CONFIG'])
except KeyError:
    # The environment variable was not set.
    # Assume we're in production (Use ProductionConfig class).
    app.config.from_object('config.ProductionConfig')

# Create the login manager.
login_manager = LoginManager()
# Initialize login_manager.
login_manager.init_app(app)

# Define the route for logging in.
login_manager.login_view = "login.login"
# Define the route for refreshing login.
login_manager.refresh_view = "login.login"
# Message flashed when logging in.
login_manager.needs_refresh_message = (
    u"To protect your account, please re authenticate to access this page."
)

# Make a database object. (Using the URI in the configuration.)
db = SQLAlchemy(app)

# Import the error handlers.
import traininglog.error

# Import the blueprints.
from traininglog.login.views import login_blueprint
from traininglog.home.views import home_blueprint
from traininglog.dashboard.views import dashboard_blueprint
from traininglog.exercise.views import exercise_blueprint
from traininglog.weight.views import weight_blueprint
from traininglog.admin.views import admin_blueprint

# Register the blueprints.
app.register_blueprint(login_blueprint)
app.register_blueprint(home_blueprint)
app.register_blueprint(dashboard_blueprint, url_prefix="/dashboard")
app.register_blueprint(exercise_blueprint, url_prefix="/exercise")
app.register_blueprint(weight_blueprint, url_prefix="/weight")
app.register_blueprint(admin_blueprint, url_prefix="/admin")

# Import the Member model.
from traininglog.models import Member

@login_manager.user_loader
def load_user(id):
    # Load (and return) the member object with the given member id = id.
    return Member.query.filter(Member.id == int(id)).first()

traininglog/admin/__init__.py
# Required for python to treat directories like packages.

traininglog/dashboard/__init__.py
# Required for python to treat directories like packages.

traininglog/dashboard/views.py
# dashboard/views.py
# Jake Malley
# 23/01/15

"""
Define the routes for the dashboard blueprint.
"""

# Imports 
from flask import render_template, Blueprint
from flask.ext.login import login_required, current_user
from traininglog.models import Exercise
from traininglog.exercise.querying_functions import *
from datetime import datetime

# Setup the dashboard blueprint.
dashboard_blueprint = Blueprint(
    'dashboard',__name__,
    template_folder='templates'
    )

# Define the routes
@dashboard_blueprint.route('/')
@login_required
def dashboard():

    # Get all the exercise data.
    exercise_data = Exercise.query.filter_by(member=current_user).order_by(Exercise.id.desc()).limit(8).all()

    # Data for the pie chart
    pie_chart_data = [{
                    'value': get_hours_running(),
                    'color':"#F7464A",
                    'highlight': "#FF5A5E",
                    'label': "Hours Running"
                },
                {
                    'value': get_hours_swimming(),
                    'color': "#46BFBD",
                    'highlight': "#5AD3D1",
                    'label': "Hours Swimming"
                },
                {
                    'value': get_hours_cycling(),
                    'color': "#FDB45C",
                    'highlight': "#FFC870",
                    'label': "Hours Cycling"
                }]

    # Data for the line chart.
    line_chart_data = [data.get_calories_burned() for data in exercise_data][::-1]
    # Empty labels for the line chart.
    line_chart_labels = [data.get_datetime() for data in exercise_data][::-1]

    # Get todays date.
    now = datetime.utcnow()

    # Get total exercised for this year.
    exercise_total_year = get_exercise_total(datetime(now.year,1,1))
    exercise_total_today = get_exercise_total(now)

    # Calculate the width of the progress bars.
    progress_today_width = int(float(exercise_total_today/4)*100)
    progress_year_width = int(float(exercise_total_today/1460)*100)

    # Render the template passing in all of the data.
    return render_template('dashboard_dashboard.html',pie_chart_data=pie_chart_data, exercise_data=exercise_data,line_chart_data=line_chart_data,line_chart_labels=line_chart_labels,exercise_total_year=exercise_total_year,exercise_total_today=exercise_total_today,progress_today_width=progress_today_width,progress_year_width=progress_year_width)

traininglog/exercise/__init__.py
# Required for python to treat directories like packages.

traininglog/exercise/views.py
# exercise/views.py
# Jake Malley
# 01/02/15

"""
Define all of the routes for the exercise blueprint.
"""

# Imports 
from flask import flash, redirect, render_template, \
                request, url_for, Blueprint, abort
from flask.ext.login import login_required, current_user
from forms import AddRunningForm, AddCyclingForm, AddSwimmingForm, CompareMemberForm, EditExerciseForm
from traininglog.models import Member, Exercise, Weight, Message, RunningLookUp, CyclingLookUp, SwimmingLookUp
from traininglog import db
from datetime import datetime, date, timedelta
from querying_functions import *
from operator import itemgetter
from traininglog.weight.views import weight_required

# Setup the exercise blueprint.
exercise_blueprint = Blueprint(
    'exercise', __name__,
    template_folder='templates'
    )

# Define the routes
@exercise_blueprint.route('/')
@login_required
def index():
    """
    Homepage for all the exercise data.
    Displays forms for adding exercise, options for generating reports 
    then a table for all the exercise.
    """

    # Create all of the forms.
    add_running_form = AddRunningForm()
    add_cycling_form = AddCyclingForm()
    add_swimming_form = AddSwimmingForm()

    # Get all the exercise data.
    exercise_data = Exercise.query.filter_by(member=current_user).order_by(Exercise.id.desc()).limit(10).all()

    # Get all the current members.
    members = Member.query.all()
    # Create the choices list for the compare form.
    choices = [(member.get_id(), member.get_full_name()) for member in members]

    # Create the form.
    compare_form = CompareMemberForm()
    compare_form.compare_member_1.choices = choices
    compare_form.compare_member_2.choices = choices

    # Display the exercise home page passing in the forms and recent data etc.
    return render_template('index.html', add_running_form=add_running_form, add_swimming_form=add_swimming_form, add_cycling_form=add_cycling_form, exercise_data=exercise_data,compare_form=compare_form)

@exercise_blueprint.route('/add_running', methods=['GET','POST'])
@login_required
@weight_required
def add_running():
    """
    Displays a form for users to add running.
    """

    # Create the running form.
    add_running_form = AddRunningForm()

    # Create empty message and error.
    message = None
    error = None

    # Make sure the method was post.
    if request.method == 'POST':
        # Validate the form.
        if add_running_form.validate_on_submit():
            
            # Get the current time.
            now = datetime.utcnow()

            # Get the all the last posts within the last minute.
            last_posts = Exercise.query.filter_by(member=current_user).filter(Exercise.date > (now-timedelta(minutes=1))).all()

            # Make sure they aren't cheating by having more than 24 hours in one day.
            # And they haven't added a post in the last 30 seconds. i.e. they aren't rapidly clicking the button.
            if (get_exercise_total(now) + float(add_running_form.duration.data) <= 24) and len(last_posts) < 5:
                # Look Up the calories burned and commit it.
                
                # Get users most recent weight.
                user_weight = Weight.query.filter_by(member=current_user).order_by(Weight.id.desc()).first().get_weight()

                calories_burned = (float(RunningLookUp.query.filter_by(id=add_running_form.exercise_level.data).first().calories_burned)/80)*user_weight*float(add_running_form.duration.data)

                # Add the exercise to the database.
                db.session.add(Exercise(now, 'running', add_running_form.exercise_level.data, add_running_form.duration.data, calories_burned, current_user.get_id()))
                # Commit the changes.
                db.session.commit()
                # Flash a success message.
                flash("Exercise successfully added.")
                # Add a well done message.
                message = "Well Done you burned "+str(calories_burned)+" calories in that session."
            else:
                # Make the correct error message.
                flash("An error occurred adding that exercise.",'error')
                if (get_exercise_total(now) + float(add_running_form.duration.data) > 24):
                    error = "Exercise has not been added as the current total for today exceeds 24 hours."
                else:
                    error = "You have tried to add too many events in the last minute, please wait then try again."

    # Get the last 4 exercises for running.
    running_data = Exercise.query.filter_by(exercise_type='running',member=current_user).order_by(Exercise.id.desc()).limit(4).all()

    # Display the add running page.
    return render_template('add_running.html', add_running_form=add_running_form, message=message,error=error,running_data=running_data)

@exercise_blueprint.route('/add_cycling', methods=['GET','POST'])
@login_required
@weight_required
def add_cycling():
    """
    Displays a form for users to add cycling.
    """

    # Create empty message and error.
    message = None
    error = None

    # Create the cycling form.
    add_cycling_form = AddCyclingForm()

    # Make sure the method was post.
    if request.method == 'POST':
        # Validate the form.
        if add_cycling_form.validate_on_submit():

            # Get the current time.
            now = datetime.utcnow()

            # Get the all the last posts within the last minute.
            last_posts = Exercise.query.filter_by(member=current_user).filter(Exercise.date > (now-timedelta(minutes=1))).all()

            # Make sure they aren't cheating by having more than 24 hours in one day.
            # And they haven't added a post in the last 30 seconds. i.e. they aren't rapidly clicking the button.
            if (get_exercise_total(now) + float(add_cycling_form.duration.data) <= 24) and len(last_posts) < 5:
                # Look Up the calories burned and commit it.
                
                # Get users most recent weight.
                user_weight = Weight.query.filter_by(member=current_user).order_by(Weight.id.desc()).first().get_weight()

                calories_burned = (float(CyclingLookUp.query.filter_by(id=add_cycling_form.exercise_level.data).first().calories_burned)/80)*user_weight*float(add_cycling_form.duration.data)
                
                # Add the exercise to the database.
                db.session.add(Exercise(now, 'cycling', add_cycling_form.exercise_level.data, add_cycling_form.duration.data, calories_burned, current_user.get_id()))
                # Commit the changes.
                db.session.commit()
                # Flash a success message.
                flash("Exercise successfully added.")
                # Add a well done message.
                message = "Well Done you burned "+str(calories_burned)+" calories in that session."
            else:
                # Make the correct error message.
                flash("An error occurred adding that exercise.",'error')
                if (get_exercise_total(now) + float(add_cycling_form.duration.data) > 24):
                    error = "Exercise has not been added as the current total for today exceeds 24 hours."
                else:
                    error = "You have tried to add too many events in the last minute, please wait then try again."

    # Get the last 4 exercises for running.
    cycling_data = Exercise.query.filter_by(exercise_type='cycling',member=current_user).order_by(Exercise.id.desc()).limit(4).all()

    # Display the add cycling page.
    return render_template('add_cycling.html', add_cycling_form=add_cycling_form, message=message,error=error, cycling_data=cycling_data)
    
@exercise_blueprint.route('/add_swimming', methods=['GET','POST'])
@login_required
@weight_required
def add_swimming():
    """
    Displays a form for users to add swimming.
    """

    # Create empty message and error.
    message = None
    error = None

    # Create the swimming form.
    add_swimming_form = AddSwimmingForm()

    # Make sure the method was post.
    if request.method == 'POST':
        # Validate the form.
        if add_swimming_form.validate_on_submit():

            # Get the current time.
            now = datetime.utcnow()

            # Get the all the last posts within the last minute.
            last_posts = Exercise.query.filter_by(member=current_user).filter(Exercise.date > (now-timedelta(minutes=1))).all()

            # Make sure they aren't cheating by having more than 24 hours in one day.
            # And they haven't added a post in the last 30 seconds. i.e. they aren't rapidly clicking the button.
            if (get_exercise_total(now) + float(add_swimming_form.duration.data) <= 24) and len(last_posts) < 5:
                # Look Up the calories burned and commit it.
                
                # Get users most recent weight.
                user_weight = Weight.query.filter_by(member=current_user).order_by(Weight.id.desc()).first().get_weight()

                calories_burned = (float(SwimmingLookUp.query.filter_by(id=add_swimming_form.exercise_level.data).first().calories_burned)/80)*user_weight*float(add_swimming_form.duration.data)
            
                # Add the exercise to the database.
                db.session.add(Exercise(now, 'swimming', add_swimming_form.exercise_level.data, add_swimming_form.duration.data, calories_burned, current_user.get_id()))
                # Commit the changes.
                db.session.commit()
                # Flash a success message.
                flash("Exercise successfully added.")
                # Add a well done message.
                message = "Well Done you burned "+str(calories_burned)+" calories in that session."
            else:
                # Make the correct error message.
                flash("An error occurred adding that exercise.",'error')

traininglog/home/__init__.py
# Required for python to treat directories like packages.

traininglog/home/views.py
# home/views.py
# Jake Malley
# 22/01/15

"""
Define the routes for the home blueprint.
"""

# Imports.
from flask import redirect, render_template, url_for, Blueprint
from traininglog.login.forms import LoginForm
from flask.ext.login import current_user

# Setup the home blueprint.
home_blueprint = Blueprint(
    'home',__name__,
    template_folder='templates'
    )

# Define the routes.
@home_blueprint.route('/')
@home_blueprint.route('/None') # Added /None as when there is a redirect error using request.referrer
def index():
    """
    If the user is logged in redirects to 
    the dashboard otherwise redirects to the 
    welcome page.
    """
    # If the user is logged in.
    if current_user.is_authenticated():
        # Redirect to the dashboard.
        return redirect(url_for('dashboard.dashboard'))
    else:
        # Redirect to the welcome page.
        return redirect(url_for('home.welcome'))

@home_blueprint.route('/welcome')
def welcome():
    """
    Renders the welcome.html template and displays it the user.
    """
    if current_user.is_authenticated():
        # Redirect to the dashboard.
        return redirect(url_for('dashboard.dashboard'))
    else:
        # Render the welcome page passing in the login form.
        return render_template('home_welcome.html',user_login_form=LoginForm())

traininglog/login/__init__.py
# Required for python to treat directories like packages.

traininglog/weight/__init__.py
# Required for python to treat directories like packages.

traininglog/templates/dashboard_layout.html
<!-- Basic layout for all other pages to inherit from when the user is logged in. -->
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Get the css styles from our styles.css style sheet. -->
        <link href="/static/css/style.css" rel="stylesheet" media="screen">
        <!-- Get the favicon from the favicon.ico file. -->
        <link rel="icon" type="image/png" href="/static/images/favicon.ico">
        <!-- Chart.js for use in the dashboard and reports. -->
        <script src="/static/js/Chart.js"></script>
    </head>
    <body class="background-with-image">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Parkwood Vale Harriers</a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-left">
                        <ol class="breadcrumb" id="navbar-breadcrumb">
                            {% block breadcrumb %}{% endblock %}
                        </ol>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Link to pick the team. -->
                        <li><a href="{{ url_for('exercise.index') }}#picktheteam">Pick the Team</a></li>
                        <!-- Messages -->
                        {% if current_user.message_data %}
                        <!-- If there is any messages -->
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span> Messages<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                {% for msg in current_user.message_data[::-1] %}
                                    <li>
										<a href="{{url_for('login.delete_message',message_id=msg.id)}}">
											<span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
											{{msg.get_message()}}
										</a>
                                    </li>
                                    <li class="divider"></li>
                                {% endfor %}
								<li>
									<a href="{{url_for('login.delete_message', message_id=0)}}">Delete All Messages</a>	
								</li>
                            </ul>
                        </li>
                        {% endif %}
                        <!-- Exercise -->
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Exercise<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('exercise.index')}}">My Exercise</a></li>
                                <li><a href="{{ url_for('exercise.view')}}">All Exercise</a></li>
                                <li class="divider"></li>
                                <li><a href="{{ url_for('exercise.add_running')}}">Add Running</a></li>
                                <li><a href="{{ url_for('exercise.add_cycling')}}">Add Cycling</a></li>
                                <li><a href="{{ url_for('exercise.add_swimming')}}">Add Swimming</a></li>
                            </ul>
                        </li>
                        <!-- User Dropdown -->
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ current_user.get_full_name() }} <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('login.myprofile')}}">My Profile</a></li>
                                <li><a href="{{ url_for('exercise.index')}}">My Exercise</a></li>
                                <li><a href="{{ url_for('weight.index')}}">My Weight</a></li>
                                <li class="divider"></li>
                                <li><a href="{{ url_for('login.myprofile')}}#change-password">Change Password</a></li>
                                <li class="divider"></li>
                                {% if current_user.is_admin %}
                                    <li><a href="{{ url_for('admin.dashboard')}}">Admin Dashboard</a></li>
                                    <li class="divider"></li>
                                {% endif %}
                                <li><a href="{{ url_for('login.logout')}}">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <div class="container">

            <!-- Content from child templates goes here. -->
            {% block content %}{% endblock %}

        </div><!-- .container -->

        <nav class="navbar navbar-default navbar-fixed-bottom">
            <div class="container">
            <p class="navbar-text">&copy; Copyright Parkwood Vale Harriers 2015</p>
            <p class="navbar-text navbar-right"></p>
            
                <!-- Display any flashed (generic messages) to the user. -->
                {% for category, message in get_flashed_messages(with_categories=true) %}
                    <p class="navbar-text pull-right">
                        {% if category == 'error' %}
                        <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                        {% else %}
                        <span class="glyphicon glyphicon-comment" style="color:#5cb85c;" aria-hidden="true"></span>
                        {% endif %}
                        {{ message }}
                    </p>
                {% endfor %}
            </div>
        </nav>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <!-- Include Bootstrap JavaScript plugins. -->
        <script src="/static/js/bootstrap.min.js"></script>
    </body>
</html>

traininglog/templates/error.html
<!-- Template page to display error messages, takes a dictionary with:
'title', 'description' and 'error_code'. Used for displaying HTML errors. -->
{% extends 'layout.html' %}
{% block title %}{% if error_dictionary %}{{ error_dictionary['title'] }}{% else %}An error occurred.{% endif%}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2" style="text-align:center;padding-top:20px;">
            <div class="text-box">
                {% if error_dictionary %}
                <!-- If the error dictionary is present, display it. -->
                    <h1>{{ error_dictionary['title'] }}</h1>
                    <p>{{ error_dictionary['description'] }}</p>
                    <br/>
                    <p>{{ error_dictionary['error_code'] }}. Please contact your system administrator.</p>
                {% else %}
                <!-- Otherwise display an unknown error -->
                    <h1>An unknown error occurred.</h1>
                    <p>Please contact your system administrator</p>
                {% endif %}
                <p> 
                    <a href="{{ url_for('home.index') }}">Go back to safety.</a>
                </p>
            </div><!-- .text-box -->
        </div><!-- .col-md-8 col-md-offset-2 -->
    </div><!-- .row -->
{% endblock %}

traininglog/templates/layout.html
<!-- Basic layout for all other pages to inherit from -->
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Get the css styles from our styles.css style sheet. -->
        <link href="/static/css/style.css" rel="stylesheet" media="screen">
        <!-- Get the favicon from the favicon.ico file. -->
        <link rel="icon" type="image/png" href="/static/images/favicon.ico">
    </head>
    <body class="background-with-image">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Parkwood Vale Harriers</a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    {% if user_login_form %}
                    <!-- Add a drop down for navigating between login and signup. -->
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('login.login') }}">Login</a></li>
                                <li><a href="{{ url_for('login.signup') }}">Sign Up</a></li>
                            </ul>
                        </li>
                    </ul>
                    <!-- If we have the login form display it -->
                    <form class="navbar-form navbar-right" role="form" method="post" action="{{ url_for('login.login') }}">
                    {{ user_login_form.csrf_token }}
                        <div class="form-group">
                            {{ user_login_form.email(class="form-control",placeholder="email",type="email") }}
                            {{ user_login_form.password(class="form-control",placeholder="password") }}
                        </div>
                        <button type="submit" class="btn btn-blue">Sign In</button>
                    </form>
                    {% else %}
                    <!-- Otherwise just display a link to the login page. -->
                    <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('home.index') }}">Home</a></li>
                    </ul>
                    {% endif %}
                    
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <div class="container">

            <!-- Content from child templates goes here. -->
            {% block content %}{% endblock %}

            <nav class="navbar navbar-default navbar-fixed-bottom">
                <div class="container">
                <p class="navbar-text">&copy; Copyright Parkwood Vale Harriers 2015</p>
                <p class="navbar-text navbar-right"></p>
                
                   <!-- Display any flashed (generic messages) to the user. -->
                    {% for category, message in get_flashed_messages(with_categories=true) %}
                        <p class="navbar-text pull-right">
                            {% if category == 'error' %}
                            <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                            {% else %}
                            <span class="glyphicon glyphicon-comment" style="color:#5cb85c;" aria-hidden="true"></span>
                            {% endif %}
                            {{ message }}
                        </p>
                    {% endfor %}
                </div>
            </nav>
        </div><!-- .container -->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <!-- Include Bootstrap JavaScript plugins. -->
        <script src="/static/js/bootstrap.min.js"></script>
    </body>
</html>