traininglog/exercise/forms.py
# exercise/forms.py
# Jake Malley
# 01/02/15

"""
Defines the forms to be used regarding exercise data.
"""

# Imports 
from flask_wtf import Form
from wtforms import TextField, SelectField, DecimalField, BooleanField
from wtforms.validators import DataRequired, NumberRange

# DataRequired validator makes sure the data is present in the field.
# NumberRange makes sure the data is between a specific number range.

class AddRunningForm(Form):

    """
    Form for users to add running.
    """

    # Select field for the exercise level.
    exercise_level = SelectField(
        'exercise_type',
        choices=[('1','5 Mph (12 Minute mile)'),
                ('2','6 Mph (10 Minute mile)'),
                ('3','7 Mph (8.5 Minute mile)'),
                ('4','8 Mph (7.5 Minute mile)'),
                ('5','9 Mph (6.5 Minute mile)'),
                ('6','10 Mph (6 Minute mile)')
                ]
    )
    # Decimal field for exercise duration.
    duration = DecimalField(
        'duration',
        places=2,
        validators=[DataRequired(), NumberRange(min=0, max=24)]
    )

class AddCyclingForm(Form):

    """
    Form for users to add cycling.
    """

    # Select field for the exercise level.
    exercise_level = SelectField(
        'exercise_type',
        choices=[('1','< 10 Mph, leisure cycling.'),
                ('2','10 - 11.9 Mph, gentle.'),
                ('3','12 - 13.9 Mph, moderate.'),
                ('4','14 - 15.9 Mph, vigorous.'),
                ('5','16 - 20 Mph, very fast.'),
                ('6','> 20 Mph, racing.')
                ]
    )
    # Decimal field for exercise duration.
    duration = DecimalField(
        'duration',
        places=2,
        validators=[DataRequired(), NumberRange(min=0, max=24)]
    )

class AddSwimmingForm(Form):

    """
    Form for users to add swimming.
    """

    # Select field for the exercise level.
    exercise_level = SelectField(
        'exercise_type',
        choices=[('1','Freestyle, Slow'),
                ('2','Freestyle Fast'),
                ('3','Backstroke'),
                ('4','Breaststroke'),
                ('5','Butterfly')
                ]
    )
    # Decimal field for exercise duration.
    duration = DecimalField(
        'duration',
        places=2,
        validators=[DataRequired(), NumberRange(min=0, max=24)]
    )

class EditExerciseForm(Form):

    """
    Form for users to change the details about their exercise.
    """

    # Hidden field for the exercise id.
    exercise_id = TextField('exercise_id')

    # Decimal field for the new duration.
    duration = DecimalField(
        'duration',
        places=2,
        validators=[DataRequired(), NumberRange(min=0, max=24)]
    )
    # Check box field for users to delete the exercise.
    delete = BooleanField('delete_exercise')


class CompareMemberForm(Form):

    """
    Form for users to select other 
    member to compare with.
    """

    # Fields to select the members to compare.
    compare_member_1 = SelectField('compare_member_1')
    compare_member_2 = SelectField('compare_member_2')

traininglog/dashboard/views.py
# dashboard/views.py
# Jake Malley
# 23/01/15

"""
Define the routes for the dashboard blueprint.
"""

# Imports 
from flask import render_template, Blueprint
from flask.ext.login import login_required, current_user
from traininglog.models import Exercise
from traininglog.exercise.querying_functions import *
from datetime import datetime

# Setup the dashboard blueprint.
dashboard_blueprint = Blueprint(
    'dashboard',__name__,
    template_folder='templates'
    )

# Define the routes
@dashboard_blueprint.route('/')
@login_required
def dashboard():

    # Get all the exercise data.
    exercise_data = Exercise.query.filter_by(member=current_user).order_by(Exercise.id.desc()).limit(8).all()

    # Data for the pie chart
    pie_chart_data = [{
                    'value': get_hours_running(),
                    'color':"#F7464A",
                    'highlight': "#FF5A5E",
                    'label': "Hours Running"
                },
                {
                    'value': get_hours_swimming(),
                    'color': "#46BFBD",
                    'highlight': "#5AD3D1",
                    'label': "Hours Swimming"
                },
                {
                    'value': get_hours_cycling(),
                    'color': "#FDB45C",
                    'highlight': "#FFC870",
                    'label': "Hours Cycling"
                }]

    # Data for the line chart.
    line_chart_data = [data.get_calories_burned() for data in exercise_data][::-1]
    # Empty labels for the line chart.
    line_chart_labels = [data.get_datetime() for data in exercise_data][::-1]

    # Get todays date.
    now = datetime.utcnow()

    # Get total exercised for this year.
    exercise_total_year = get_exercise_total(datetime(now.year,1,1))
    exercise_total_today = get_exercise_total(now)

    # Calculate the width of the progress bars.
    progress_today_width = int(float(exercise_total_today/4)*100)
    progress_year_width = int(float(exercise_total_today/1460)*100)

    # Render the template passing in all of the data.
    return render_template('dashboard_dashboard.html',pie_chart_data=pie_chart_data, exercise_data=exercise_data,line_chart_data=line_chart_data,line_chart_labels=line_chart_labels,exercise_total_year=exercise_total_year,exercise_total_today=exercise_total_today,progress_today_width=progress_today_width,progress_year_width=progress_year_width)

traininglog/exercise/__init__.py
# Required for python to treat directories like packages.

traininglog/exercise/views.py
# exercise/views.py
# Jake Malley
# 01/02/15

"""
Define all of the routes for the exercise blueprint.
"""

# Imports 
from flask import flash, redirect, render_template, \
                request, url_for, Blueprint, abort
from flask.ext.login import login_required, current_user
from forms import AddRunningForm, AddCyclingForm, AddSwimmingForm, CompareMemberForm, EditExerciseForm
from traininglog.models import Member, Exercise, Weight, Message, RunningLookUp, CyclingLookUp, SwimmingLookUp
from traininglog import db
from datetime import datetime, date, timedelta
from querying_functions import *
from operator import itemgetter
from traininglog.weight.views import weight_required

# Setup the exercise blueprint.
exercise_blueprint = Blueprint(
    'exercise', __name__,
    template_folder='templates'
    )

# Define the routes
@exercise_blueprint.route('/')
@login_required
def index():
    """
    Homepage for all the exercise data.
    Displays forms for adding exercise, options for generating reports 
    then a table for all the exercise.
    """

    # Create all of the forms.
    add_running_form = AddRunningForm()
    add_cycling_form = AddCyclingForm()
    add_swimming_form = AddSwimmingForm()

    # Get all the exercise data.
    exercise_data = Exercise.query.filter_by(member=current_user).order_by(Exercise.id.desc()).limit(10).all()

    # Get all the current members.
    members = Member.query.all()
    # Create the choices list for the compare form.
    choices = [(member.get_id(), member.get_full_name()) for member in members]

    # Create the form.
    compare_form = CompareMemberForm()
    compare_form.compare_member_1.choices = choices
    compare_form.compare_member_2.choices = choices

    # Display the exercise home page passing in the forms and recent data etc.
    return render_template('index.html', add_running_form=add_running_form, add_swimming_form=add_swimming_form, add_cycling_form=add_cycling_form, exercise_data=exercise_data,compare_form=compare_form)

@exercise_blueprint.route('/add_running', methods=['GET','POST'])
@login_required
@weight_required
def add_running():
    """
    Displays a form for users to add running.
    """

    # Create the running form.
    add_running_form = AddRunningForm()

    # Create empty message and error.
    message = None
    error = None

    # Make sure the method was post.
    if request.method == 'POST':
        # Validate the form.
        if add_running_form.validate_on_submit():
            
            # Get the current time.
            now = datetime.utcnow()

            # Get the all the last posts within the last minute.
            last_posts = Exercise.query.filter_by(member=current_user).filter(Exercise.date > (now-timedelta(minutes=1))).all()

            # Make sure they aren't cheating by having more than 24 hours in one day.
            # And they haven't added a post in the last 30 seconds. i.e. they aren't rapidly clicking the button.
            if (get_exercise_total(now) + float(add_running_form.duration.data) <= 24) and len(last_posts) < 5:
                # Look Up the calories burned and commit it.
                
                # Get users most recent weight.
                user_weight = Weight.query.filter_by(member=current_user).order_by(Weight.id.desc()).first().get_weight()

                calories_burned = (float(RunningLookUp.query.filter_by(id=add_running_form.exercise_level.data).first().calories_burned)/80)*user_weight*float(add_running_form.duration.data)

                # Add the exercise to the database.
                db.session.add(Exercise(now, 'running', add_running_form.exercise_level.data, add_running_form.duration.data, calories_burned, current_user.get_id()))
                # Commit the changes.
                db.session.commit()
                # Flash a success message.
                flash("Exercise successfully added.")
                # Add a well done message.
                message = "Well Done you burned "+str(calories_burned)+" calories in that session."
            else:
                # Make the correct error message.
                flash("An error occurred adding that exercise.",'error')
                if (get_exercise_total(now) + float(add_running_form.duration.data) > 24):
                    error = "Exercise has not been added as the current total for today exceeds 24 hours."
                else:
                    error = "You have tried to add too many events in the last minute, please wait then try again."

    # Get the last 4 exercises for running.
    running_data = Exercise.query.filter_by(exercise_type='running',member=current_user).order_by(Exercise.id.desc()).limit(4).all()

    # Display the add running page.
    return render_template('add_running.html', add_running_form=add_running_form, message=message,error=error,running_data=running_data)

@exercise_blueprint.route('/add_cycling', methods=['GET','POST'])
@login_required
@weight_required
def add_cycling():
    """
    Displays a form for users to add cycling.
    """

    # Create empty message and error.
    message = None
    error = None

    # Create the cycling form.
    add_cycling_form = AddCyclingForm()

    # Make sure the method was post.
    if request.method == 'POST':
        # Validate the form.
        if add_cycling_form.validate_on_submit():

            # Get the current time.
            now = datetime.utcnow()

            # Get the all the last posts within the last minute.
            last_posts = Exercise.query.filter_by(member=current_user).filter(Exercise.date > (now-timedelta(minutes=1))).all()

            # Make sure they aren't cheating by having more than 24 hours in one day.
            # And they haven't added a post in the last 30 seconds. i.e. they aren't rapidly clicking the button.
            if (get_exercise_total(now) + float(add_cycling_form.duration.data) <= 24) and len(last_posts) < 5:
                # Look Up the calories burned and commit it.
                
                # Get users most recent weight.
                user_weight = Weight.query.filter_by(member=current_user).order_by(Weight.id.desc()).first().get_weight()

                calories_burned = (float(CyclingLookUp.query.filter_by(id=add_cycling_form.exercise_level.data).first().calories_burned)/80)*user_weight*float(add_cycling_form.duration.data)
                
                # Add the exercise to the database.
                db.session.add(Exercise(now, 'cycling', add_cycling_form.exercise_level.data, add_cycling_form.duration.data, calories_burned, current_user.get_id()))
                # Commit the changes.
                db.session.commit()
                # Flash a success message.
                flash("Exercise successfully added.")
                # Add a well done message.
                message = "Well Done you burned "+str(calories_burned)+" calories in that session."
            else:
                # Make the correct error message.
                flash("An error occurred adding that exercise.",'error')
                if (get_exercise_total(now) + float(add_cycling_form.duration.data) > 24):
                    error = "Exercise has not been added as the current total for today exceeds 24 hours."
                else:
                    error = "You have tried to add too many events in the last minute, please wait then try again."

    # Get the last 4 exercises for running.
    cycling_data = Exercise.query.filter_by(exercise_type='cycling',member=current_user).order_by(Exercise.id.desc()).limit(4).all()

    # Display the add cycling page.
    return render_template('add_cycling.html', add_cycling_form=add_cycling_form, message=message,error=error, cycling_data=cycling_data)
    
@exercise_blueprint.route('/add_swimming', methods=['GET','POST'])
@login_required
@weight_required
def add_swimming():
    """
    Displays a form for users to add swimming.
    """

    # Create empty message and error.
    message = None
    error = None

    # Create the swimming form.
    add_swimming_form = AddSwimmingForm()

    # Make sure the method was post.
    if request.method == 'POST':
        # Validate the form.
        if add_swimming_form.validate_on_submit():

            # Get the current time.
            now = datetime.utcnow()

            # Get the all the last posts within the last minute.
            last_posts = Exercise.query.filter_by(member=current_user).filter(Exercise.date > (now-timedelta(minutes=1))).all()

            # Make sure they aren't cheating by having more than 24 hours in one day.
            # And they haven't added a post in the last 30 seconds. i.e. they aren't rapidly clicking the button.
            if (get_exercise_total(now) + float(add_swimming_form.duration.data) <= 24) and len(last_posts) < 5:
                # Look Up the calories burned and commit it.
                
                # Get users most recent weight.
                user_weight = Weight.query.filter_by(member=current_user).order_by(Weight.id.desc()).first().get_weight()

                calories_burned = (float(SwimmingLookUp.query.filter_by(id=add_swimming_form.exercise_level.data).first().calories_burned)/80)*user_weight*float(add_swimming_form.duration.data)
            
                # Add the exercise to the database.
                db.session.add(Exercise(now, 'swimming', add_swimming_form.exercise_level.data, add_swimming_form.duration.data, calories_burned, current_user.get_id()))
                # Commit the changes.
                db.session.commit()
                # Flash a success message.
                flash("Exercise successfully added.")
                # Add a well done message.
                message = "Well Done you burned "+str(calories_burned)+" calories in that session."
            else:
                # Make the correct error message.
                flash("An error occurred adding that exercise.",'error')

traininglog/exercise/templates/add_cycling.html
<!-- Display add cycling page to the users. -->
{% extends 'dashboard_layout.html' %}
{% block title %}Add Cycling{% endblock %}
{%block breadcrumb %}
<li><a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a></li>
<li><a href="{{ url_for('exercise.index') }}">Exercise</a></li>
<li class="active">Add Cycling</li>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-4 col-md-offset-4" style="padding-top:20px;">
    <div class="text-box">
        <a href="{{ url_for('exercise.index') }}">Back</a>
        <div class="page-header">
            <h1>Exercise<br/><small>Cycling</small></h1>
        </div>

        <!-- If there is an error display it to the user. -->
        {% if error %}
            <p class="alert alert-danger">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                {{ error }}
            </p>
        <!-- If there is a message display it to the user. -->
        {% elif message %}
            <p class="alert alert-success">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                {{ message }}
            </p>
        {% endif %}

        <!-- Include the form -->
        {% include 'add_cycling_form.html' %}

        <!-- Display recent exercise -->
        <div class="page-header">
            <h1><small>Recent Cycling</small></h1>
        </div>
        <table class="table table-hover">
            {% for data in cycling_data %}
            <tr>
                <td><a href="{{ url_for('exercise.view_exercise',exercise_id=data.id) }}">{{ data.get_date() }} - Calories Burnt {{ data.get_calories_burned() }}</a></td>
            </tr>
            {% endfor %}
        </table>

    </div><!-- .text-box -->
  </div><!-- .col-md-4 col-md-offset-4 -->
</div><!-- .row -->
{% endblock %}

traininglog/exercise/templates/add_cycling_form.html
<!-- Form to add cycling. -->
<form role="form" method="post" action="{{ url_for('exercise.add_cycling') }}">
    {{ add_cycling_form.csrf_token }}
    <div class="form-group">
        <label>Exercise Level</label>
        {{ add_cycling_form.exercise_level(class="form-control") }}
        {% for error in add_cycling_form.exercise_level.errors %}
            <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
            {{ error }}
        {% endfor %}
    </div>
    <div class="form-group">
        {{ add_cycling_form.duration(class="form-control",placeholder="Duration (in Hours)") }}
        {% for error in add_cycling_form.duration.errors %}
            <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
            {{ error }}
        {% endfor %}
    </div>
    <button class="btn btn-blue" type="submit">Add Exercise</button>
</form>

traininglog/exercise/templates/add_running.html
<!-- Display add running page to the users. -->
{% extends 'dashboard_layout.html' %}
{% block title %}Add Running{% endblock %}
{%block breadcrumb %}
<li><a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a></li>
<li><a href="{{ url_for('exercise.index') }}">Exercise</a></li>
<li class="active">Add Running</li>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-4 col-md-offset-4" style="padding-top:20px;">
    <div class="text-box">
        <a href="{{ url_for('exercise.index') }}">Back</a>
        <div class="page-header">
            <h1>Exercise<br/><small>Running</small></h1>
        </div>

        <!-- If there is an error display it to the user. -->
        {% if error %}
            <p class="alert alert-danger">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                {{ error }}
            </p>
        <!-- If there is a message display it to the user. -->
        {% elif message %}
            <p class="alert alert-success">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                {{ message }}
            </p>
        {% endif %}

        <!-- Include the form -->
        {% include 'add_running_form.html' %}

        <!-- Display recent exercise -->
        <div class="page-header">
            <h1><small>Recent Running</small></h1>
        </div>
        <table class="table table-hover">
            {% for data in running_data %}
            <tr>
                <td><a href="{{ url_for('exercise.view_exercise',exercise_id=data.id) }}">{{ data.get_date() }} - Calories Burnt {{ data.get_calories_burned() }}</a></td>
            </tr>
            {% endfor %}
        </table>
        
    </div><!-- .text-box -->
  </div><!-- .col-md-4 col-md-offset-4 -->
</div><!-- .row -->
{% endblock %}

traininglog/exercise/templates/add_swimming.html
<!-- Display add swimming page to the users. -->
{% extends 'dashboard_layout.html' %}
{% block title %}Add Swimming{% endblock %}
{%block breadcrumb %}
<li><a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a></li>
<li><a href="{{ url_for('exercise.index') }}">Exercise</a></li>
<li class="active">Add Running</li>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-4 col-md-offset-4" style="padding-top:20px;">
    <div class="text-box">
        <a href="{{ url_for('exercise.index') }}">Back</a>
        <div class="page-header">
            <h1>Exercise<br/><small>Swimming</small></h1>
        </div>

        <!-- If there is an error display it to the user. -->
        {% if error %}
            <p class="alert alert-danger">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                {{ error }}
            </p>
        <!-- If there is a message display it to the user. -->
        {% elif message %}
            <p class="alert alert-success">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                {{ message }}
            </p>
        {% endif %}

        <!-- Include the form -->
        {% include 'add_swimming_form.html' %}

        <!-- Display recent exercise -->
        <div class="page-header">
            <h1><small>Recent Swimming</small></h1>
        </div>
        <table class="table table-hover">
            {% for data in swimming_data %}
            <tr>
                <td><a href="{{ url_for('exercise.view_exercise',exercise_id=data.id) }}">{{ data.get_date() }} - Calories Burnt {{ data.get_calories_burned() }}</a></td>
            </tr>
            {% endfor %}
        </table>

    </div><!-- .text-box -->
  </div><!-- .col-md-4 col-md-offset-4 -->
</div><!-- .row -->
{% endblock %}

traininglog/exercise/templates/exercise_picktheteam.html
<!-- Display the pick the team page to the users. -->
{% extends 'dashboard_layout.html' %}
{% block title %}Pick the Team{% endblock %}
{%block breadcrumb %}
<li><a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a></li>
<li><a href="{{ url_for('exercise.index') }}">Exercise</a></li>
<li class="active">Pick the Team</li>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-8 col-md-offset-2" style="padding-top:20px;">
    <div class="text-box">
        <a href="{{ url_for('exercise.index') }}">Back</a>
        <!-- Page Header -->
        <div class="page-header">
            <h1>{{ page_title }}</h1>
        </div>
        <!-- Table to show the team. -->
        <table class="table table-hover">
            <tr>
                <th>Member:</th>
                <th>Total Calories Burned:</th>
                <th>Total Hours Exercised:</th>
            </tr>
            <!-- Get the top 8 members. -->
            {% for member in members_ordered[:8] %}
            <tr>
                <td>
                <!-- If the member has exercise data, link to their first bit of data. -->
                {% if member[0].exercise_data %}
                <a href="{{url_for('exercise.view_exercise', exercise_id=member[0].exercise_data[-1].id)}}">{{ member[0].get_full_name() }}</a>
                {%else%}
                <!-- If they have no exercise data. -->
                <a href="#">{{ member[0].get_full_name() }}</a>
                {% endif %}
                </td>
                <td>{{ member[1] }} Calories</td>
                <td>{{ member[2] }} Hours</td>
            </tr>
            {% endfor %}
            <!-- If we are not picking the team. -->
            {% if not pick_team %}
                <!-- Display the rest of the members. -->
                {% for member in members_ordered[8:] %}
                <tr>
                    <td>
                    <!-- If the member has exercise data, link to their first bit of data. -->
                    {% if member[0].exercise_data %}
                    <a href="{{url_for('exercise.view_exercise', exercise_id=member[-1].exercise_data[0].id)}}">{{ member[0].get_full_name() }}</a>
                    {%else%}
                    <!-- If they have no exercise data. -->
                    <a href="#">{{ member[0].get_full_name() }}</a>
                    {% endif %}
                    </td>
                    <td>{{ member[1] }} Calories</td>
                    <td>{{ member[2] }} Hours</td>
                </tr>
                {% endfor %}
            {% endif %}
        </table>
    </div><!-- .text-box -->
  </div><!-- .col-md-8 col-md-offset-2 -->
</div><!-- .row -->
{% endblock %}

traininglog/exercise/templates/index.html
<!-- Display add exercise page to the users. -->
{% extends 'dashboard_layout.html' %}
{% block title %}Add New Exercise{% endblock %}
{%block breadcrumb %}
<li><a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a></li>
<li class="active">Exercise</li>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-8 col-md-offset-2" style="padding-top:20px;">
    <div class="text-box">
        <a href="{{ url_for('dashboard.dashboard') }}">Back</a>
        <div class="page-header">
            <h1>My Exercise</h1>
            <p>Here you can add new exercise events.</p>
        </div>
        <!-- Forms -->
        <div class="row">
            <div class="col-md-4">
                <h2>Swimming</h2>
                <p><a href="{{ url_for('exercise.add_swimming') }}">View recent swimming</a></p>
                {% include 'add_swimming_form.html' %}
            </div>
            
            <div class="col-md-4">
                <h2>Running</h2>
                <p><a href="{{ url_for('exercise.add_running') }}">View recent running</a></p>
                {% include 'add_running_form.html' %}
            </div>
            <div class="col-md-4">
                <h2>Cycling</h2>
                <p><a href="{{ url_for('exercise.add_cycling') }}">View recent cycling</a></p>
                {% include 'add_cycling_form.html' %}
            </div>
        </div>

        <!-- Display compare form -->
        <div class="page-header" id="compare">
            <h1><small>Compare Members</small></h1>
            <p>You can use this form to compare the all time performance of two members.</p>
        </div>
        <form role="form" class="form-inline" method="post" action="{{ url_for('exercise.compare') }}">
            {{ compare_form.csrf_token }}
            <div class="form-group" style="margin-right:5px;">
                <label>Member 1</label>
                {{ compare_form.compare_member_1(class="form-control") }}
                {% for error in compare_form.compare_member_1.errors %}
                    <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                    {{ error }}
                {% endfor %}
            </div>
            <div class="form-group" style="margin-left:5px;">
                <label>Against Member 2</label>
                {{ compare_form.compare_member_2(class="form-control") }}
                {% for error in compare_form.compare_member_2.errors %}
                    <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                    {{ error }}
                {% endfor %}
            </div>
            <button class="btn btn-blue" type="submit">Compare Members</button>
        </form>

        <!-- Display Pick the Team links. -->
        <div class="page-header" id="picktheteam">
            <h1><small>Pick the Team</small></h1>
        </div>
        <div class="row" style="text-align:center;">
            <div class="col-md-4">
                <label>Ranked by Calories Burned</label>
            </div>
            <div class="col-md-4">
                <a class="btn btn-blue" href="{{url_for('exercise.picktheteam', all='false',order_by='calories')}}" role="button">Pick the Team </a>
            </div>
            <div class="col-md-4">
                <a class="btn btn-blue" href="{{url_for('exercise.picktheteam', all='true', order_by='calories')}}" role="button">Rank all Members</a>
            </div>
        </div>
        <br/>
        <div class="row" style="text-align:center;">
            <div class="col-md-4">
                <label>Ranked by Hours Exercised</label>
            </div>
            <div class="col-md-4">
                <a class="btn btn-blue" href="{{url_for('exercise.picktheteam', all='false', order_by='hours')}}" role="button">Pick the Team </a>
            </div>
            <div class="col-md-4">
                <a class="btn btn-blue" href="{{url_for('exercise.picktheteam', all='true', order_by='hours')}}" role="button">Rank all Members</a>
            </div>
        </div>

        <!-- Display recent exercise -->
        <div class="page-header" id="recentexercise">
            <h1><small>Recent Exercise</small></h1>
            <p>Here are your last ten exercise events.</p>
        </div>
        
        <!-- Show the last 3 entries -->
        <table class="table table-hover">
            <tr>
                <th>Date</th>
                <th>Exercise</th>
                <th>Duration</th>
                <th>Calories Burned</th>
            </tr>
            {% for data in exercise_data[:3] %}
            <tr>
                <td><a href="{{ url_for('exercise.view_exercise',exercise_id=data.id) }}">{{ data.get_date() }}</a></td>
                <td>{{ data.get_exercise() }}</td>
                <td>{{ data.exercise_duration }} Hour(s)</td>
                <td>{{ data.calories_burned }} Calories</td>
            </tr>
            {% endfor %}
        </table>


        <!-- If there is more than 3 items display the more section. -->
        {% if exercise_data[3:] %}
        <button class="btn btn-blue" type="button" data-toggle="collapse" data-target="#all_data_collapse" aria-expanded="false" aria-controls="all_data_collapse">
            More...
        </button>

        <!-- The rest of exercise data hidden in a collapse. -->
        <div class="collapse" id="all_data_collapse" style="margin-top:10px;">
            <div class="well">
                <table class="table table-hover">
                    <tr>
                        <th>Date</th>
                        <th>Exercise</th>
                        <th>Duration</th>
                        <th>Calories Burned</th>
                    </tr>
                    {% for data in exercise_data[3:] %}
                    <tr>
                        <td><a href="{{ url_for('exercise.view_exercise',exercise_id=data.id) }}">{{ data.get_date() }}</a></td>
                        <td>{{ data.get_exercise() }}</td>
                        <td>{{ data.exercise_duration }} Hour(s)</td>
                        <td>{{ data.calories_burned }} Calories</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        {% endif %}
        
    </div><!-- .text-box -->
  </div><!-- .col-md-8 col-md-offset-2 -->
</div><!-- .row -->
{% endblock %}