traininglog/admin/views.py
# admin/views.py
# Jake Malley
# 19/02/15

"""
Define the routes for the admin blueprint.
"""

# Imports
from flask import redirect, render_template, \
                request, url_for, Blueprint, abort, flash
from flask.ext.login import fresh_login_required, current_user
from traininglog import db
from traininglog.models import Member, Exercise
from forms import AdminEditDetailsForm
from functools import wraps
from datetime import datetime

# Setup the admin blueprint.
admin_blueprint = Blueprint(
    'admin',__name__,
    template_folder='templates'
    )

# Admin Required - Only allows members with is_admin = 1 to access these views.
# Allows me to use the decorator @admin_required on different routes.
def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        # If they are not an admin take them home.
        if not bool(current_user.is_admin):
            return redirect(url_for('home.index'))
        return f(*args, **kwargs)
    return decorated_function

# Define the routes
@admin_blueprint.route('/')
@fresh_login_required
@admin_required
def dashboard():
    """
    The dashboard for the admin blueprint.
    """

    # Get a list of all the members.
    members = Member.query.all()
    # Get a list of all the active members. (Members who have logged in today.)
    active_members = Member.query.filter(Member.last_login_date>datetime.utcnow().date()).all()
    # Create a dictionary of the stats.
    stats = {
                "total_members":len(members), # Total number of members.
                "active_members":len(active_members) # Total number of active members.
            }

    # Render the admin index page passing in the members and stats.
    return render_template('admin_index.html', members=members,stats=stats)

@admin_blueprint.route('/view/<member_id>', methods=['POST','GET'])
@fresh_login_required
@admin_required
def view(member_id):
    """
    Method for viewing individual users.
    """

    # Create the form to edit the members data.
    admin_edit_form = AdminEditDetailsForm()
    # If the method was post and the form was valid.
    if request.method == 'POST' and admin_edit_form.validate_on_submit():
        # Change the data.

        # Get the member with that ID.
        member = Member.query.filter_by(id=admin_edit_form.member_id.data).first()

        # See if the account was marked to be delete as then we don't need to update the details as well.
        if bool(admin_edit_form.delete_user.data) == True:
            # Delete the user.
            
            # Get their exercise data. 
            exercise_data = Exercise.query.filter_by(member=member).all()
            # For each piece of data.
            for data in exercise_data:
                # Delete the data.
                db.session.delete(data)

            # Finally delete the user.
            db.session.delete(member)
            # And commit the changes
            db.session.commit()

            # Flash a message.
            flash('Account has been delete!')

            # Redirect to the admin dashboard sicne that user doesn't exist anymore.
            return redirect(url_for('admin.dashboard'))

        else:
            # User was not marked as deleted, 
            # update their details with the details from the form.
            member.firstname = admin_edit_form.firstname.data
            member.surname = admin_edit_form.surname.data
            member.email = admin_edit_form.email.data
            member.set_active_status(int(admin_edit_form.set_active.data))
            member.is_admin = int(admin_edit_form.set_admin.data)

            # If the password was changed.
            if admin_edit_form.password.data:
                # Update the password.
                member.update_password(admin_edit_form.password.data)

            # Flash a success message.
            flash("Details have been updated. Please inform the member of the changes.")

        # Commit the changes.
        db.session.commit()

        # Refresh the page
        return render_template('admin_view.html', member=member, admin_edit_form=admin_edit_form)

    else:

        # Get the member with that ID.
        member = Member.query.filter_by(id=member_id).first()

        # If that member exists.
        if member is not None:
			# Render the template passing in the member and form.
            return render_template('admin_view.html', member=member, admin_edit_form=admin_edit_form)
        else:
			# Raise a HTTP 404 (Page not found) error.
            abort(404)

traininglog/dashboard/views.py
# dashboard/views.py
# Jake Malley
# 23/01/15

"""
Define the routes for the dashboard blueprint.
"""

# Imports 
from flask import render_template, Blueprint
from flask.ext.login import login_required, current_user
from traininglog.models import Exercise
from traininglog.exercise.querying_functions import *
from datetime import datetime

# Setup the dashboard blueprint.
dashboard_blueprint = Blueprint(
    'dashboard',__name__,
    template_folder='templates'
    )

# Define the routes
@dashboard_blueprint.route('/')
@login_required
def dashboard():

    # Get all the exercise data.
    exercise_data = Exercise.query.filter_by(member=current_user).order_by(Exercise.id.desc()).limit(8).all()

    # Data for the pie chart
    pie_chart_data = [{
                    'value': get_hours_running(),
                    'color':"#F7464A",
                    'highlight': "#FF5A5E",
                    'label': "Hours Running"
                },
                {
                    'value': get_hours_swimming(),
                    'color': "#46BFBD",
                    'highlight': "#5AD3D1",
                    'label': "Hours Swimming"
                },
                {
                    'value': get_hours_cycling(),
                    'color': "#FDB45C",
                    'highlight': "#FFC870",
                    'label': "Hours Cycling"
                }]

    # Data for the line chart.
    line_chart_data = [data.get_calories_burned() for data in exercise_data][::-1]
    # Empty labels for the line chart.
    line_chart_labels = [data.get_datetime() for data in exercise_data][::-1]

    # Get todays date.
    now = datetime.utcnow()

    # Get total exercised for this year.
    exercise_total_year = get_exercise_total(datetime(now.year,1,1))
    exercise_total_today = get_exercise_total(now)

    # Calculate the width of the progress bars.
    progress_today_width = int(float(exercise_total_today/4)*100)
    progress_year_width = int(float(exercise_total_today/1460)*100)

    # Render the template passing in all of the data.
    return render_template('dashboard_dashboard.html',pie_chart_data=pie_chart_data, exercise_data=exercise_data,line_chart_data=line_chart_data,line_chart_labels=line_chart_labels,exercise_total_year=exercise_total_year,exercise_total_today=exercise_total_today,progress_today_width=progress_today_width,progress_year_width=progress_year_width)

traininglog/admin/templates/admin_index.html
<!-- Display admin dashboard page to the users. -->
{% extends 'dashboard_layout.html' %}
{% block title %}Admin{% endblock %}
{%block breadcrumb %}
<li><a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a></li>
<li class="active">Admin</li>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-12" style="padding-top:20px;">
    <div class="text-box">
        <div class="page-header">
            <h1>Admin</h1>
        </div>
        <p>Parkwood Vale Harriers Admin Area.</p>

        <table class="table table-hover">
            <tr>
            <td class="success">Administrators Accounts.</td>
            <td class="warning">Inactive Accounts.</td>
            <td>Normal Accounts.</td>
            </tr>
        </table>

        <table class="table table-hover">
            <tr>
                <th>Registered Users:</th>
                <th>Total:</th>
                <td>{{ stats["total_members"] }}</td>
                <th>Active:</th>
                <td>{{ stats["active_members"] }}</td>
                <td></td>
            </tr>
            <tr>
                <th>ID</th>
                <th>Firstname</th>
                <th>Surname</th>
                <th>E-Mail</th>
                <th>Join Date</th>
                <th>Last Login Date</th>
            </tr>
            {% for member in members %}
            {% if not member.is_active() %}
            <tr class="warning">
            {% elif member.is_administrator() %}
            <tr class="success">
            {% else %}
            <tr>
            {% endif %}
                <td><a href="{{ url_for('admin.view', member_id=member.get_id()) }}">{{ member.get_id() }}</a></td>
                <td>{{ member.get_firstname() }}</td>
                <td>{{ member.get_surname() }}</td>
                <td>{{ member.get_email() }}</td>
                <td>{{ member.get_join_date() }}</td>
                <td>{{ member.get_last_login_date() }}</td>
            </tr>
            {% endfor %}
        </table>
    </div><!-- .text-box -->
  </div><!-- .col-md-12 -->
</div><!-- .row -->
{% endblock %}

traininglog/admin/templates/admin_view.html
<!-- Display admin dashboard page to the users. -->
{% extends 'dashboard_layout.html' %}
{% block title %}Admin{% endblock %}
{%block breadcrumb %}
<li><a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a></li>
<li><a href="{{ url_for('admin.dashboard') }}">Admin</a></li>
<li class="active">View Member</li>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-12" style="padding-top:20px;">
    <div class="text-box">
        <div class="page-header">
            <h1>View Member<br/>
                <small>{{member.get_full_name()}} 
                  {%if member.exercise_data %}
                    <a href="{{url_for('exercise.view_exercise', exercise_id=member.exercise_data[0].id)}}">View Exercise</a>
                  {% endif %}
                </small>
            </h1>
        </div>
          <!-- Errors from the editDetailsForm in the Modal. -->
          {% for field, errors in admin_edit_form.errors.items() %}
              <p><span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
              The {{ field }} field had the following error: {{ errors[0] }}</p>
          {% endfor %}
          <form class="form-horizontal" id="adminEditDetailsForm" method="POST" action="">
            {{ admin_edit_form.csrf_token }}
            {{ admin_edit_form.member_id(type="hidden",value=member.get_id()) }}
            <div class="form-group">
              <label class="col-sm-2 control-label">Firstname</label>
              <div class="col-sm-10">
                {{ admin_edit_form.firstname(class="form-control",value=member.get_firstname()) }}
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Surname</label>
              <div class="col-sm-10">
                {{ admin_edit_form.surname(class="form-control",value=member.get_surname()) }}
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Email</label>
              <div class="col-sm-10">
                {{ admin_edit_form.email(class="form-control",value=member.get_email()) }}
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Weight</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" value="{% if member.weight_data %}{{member.weight_data[-1].weight}} Kilograms{% else %}No weight data could be found.{%endif %}" disabled="true">
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Height</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" value="{{member.get_height()}} Meters" disabled="true">
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Gender</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" value="{{member.get_gender()}}" disabled="true">
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Address</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" value="{{member.get_address()}}" disabled="true">
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Password</label>
              <div class="col-sm-10">
                {{ admin_edit_form.password(class="form-control") }}
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Confirm Password</label>
              <div class="col-sm-10">
                {{ admin_edit_form.confirm_password(class="form-control") }}
              </div>
            </div>
            <div class="checkbox">
              <label class="col-sm-2 control-label">Set Admin</label>
              <div class="col-sm-10">
                <label>
                {% if member.is_admin %}
                  {{ admin_edit_form.set_admin(checked="checked") }}
                {%else %}
                  {{ admin_edit_form.set_admin() }}
                {%endif%}
                </label>
              </div>
            </div>
            <div class="checkbox">
              <label class="col-sm-2 control-label">Set Active</label>
              <div class="col-sm-10">
                <label>
                {% if member.account_is_active %}
                  {{ admin_edit_form.set_active(checked="checked") }}
                {%else %}
                  {{ admin_edit_form.set_active() }}
                {%endif%}
                </label>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Join Date</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" value="{{member.get_join_date()}}" disabled="true">
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Last Login</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" value="{{member.get_last_login_date()}}" disabled="true">
              </div>
            </div>
			<div class="checkbox">	
				<div class="col-sm-10 col-sm-offset-2">
				  <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
            <strong>Delete Account</strong>
						These actions cannot be undone.
            <label>{{ admin_edit_form.delete_user() }}</label>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
				{% if member == current_user %}
					<button class="btn btn-default" disabled="true">Save Changes</button> 
					<label>Cannot make changes to your own profile via the admin dashboard.</label>
				{% else %}
					<button type="button" class="btn btn-blue" data-toggle="modal" data-target="#confirmChanges">
						Save Changes
					</button>
				{% endif %}
				</div>
			</div>
		</form>

          <!-- Confirmation Modal -->
          <div class="modal fade" id="confirmChanges" tabindex="-1" role="dialog" aria-labelledby="confirmChanges" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="confirmChanges">Confirm Changes</h4>
                </div>
                <div class="modal-body">
                  Changing a member's details may result in them being unable to login and access their account. As well as damage to this system. Don't abuse your administrator privileges!
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <button class="btn btn-danger" type="submit" onclick=" $('#adminEditDetailsForm').submit();">Confirm Changes</button>
                </div>
              </div>
            </div>
          </div>
        
    </div><!-- .text-box -->
  </div><!-- .col-md-12 -->
</div><!-- .row -->
{% endblock %}