traininglog/login/forms.py
# login/forms.py
# Jake Malley
# 19/01/15

"""
Defines all the forms used in the login blueprint.
"""

# Imports
from flask_wtf import Form
from wtforms import TextField, PasswordField, SelectField, DecimalField, BooleanField
from wtforms.validators import StopValidation,DataRequired, Email, Length, EqualTo, NumberRange

# DataRequired validator makes sure the data is present in the field.
# Length validator makes sure the field is between a specific lenght
# EqualTo validator makes sure the field is equal to another field.
# Email validator makes sure the field is a valid email.  
# NumberRange makes sure the data is between a specific number range.

def is_a_float(form, field):
    """
    Validator to check the field is a float.
    """
    if field.data is not None:
        try:
            # Try to convert the field to a float.
            float(field.data)
        except ValueError:
            # The field is not a float.
            field.errors[:] = ['Must be a numerical value.']
            # Stop all further validations.
            raise StopValidation()
    else:
        # The field is not a float.
        field.errors[:] = ['This field is required and must be a numerical value.']
        # Stop all further validations.
        raise StopValidation()

def is_alpha_numeric(form, field):
    """
    Validator to check the field is alpha numeric.
    """
    if field.data is not None and not str(field.data).replace(' ','').isalnum():
        # The field is not a float.
        field.errors[:] = ['Must be and alpha-numerical string, and not contain symbols.']
        # Stop all further validations.
        raise StopValidation()

class LoginForm(Form):

    """
    Form for users to login to the site.
    """

    # Text field for the users email.
    email = TextField('email',validators=[DataRequired(),Email(message=None),Length(max=50)])
    
    # Password field for the users password.
    password = PasswordField('password',validators=[DataRequired(),Length(max=32)])

    # Remember Me field.
    remember = BooleanField('remember me')

class SignUpForm(Form):

    """
    Form for users to signup to the site.
    """ 

    # Text field for the users firstname.
    firstname = TextField(
        'firstname', 
        validators=[DataRequired(),Length(min=2,max=20)]
    )
    # Text field for the users surname.
    surname = TextField(
        'surname', 
        validators=[DataRequired(), Length(min=2,max=20)]
    )
    # Text field for the users email.
    email = TextField(
        'email',
        validators=[DataRequired(),Email(message=None),Length(max=50)]
    )
    # Password field for the users chosen password.
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6,max=32)]
    )
    # Password confirmation field.
    password_confirm = PasswordField(
        'password confirmation',
        validators=[DataRequired(),EqualTo('password', message='Passwords must match.')]
    )
    # Select field for selecting gender.
    gender = SelectField(
        'gender', 
        choices=[('male','Male'),('female','Female')]
    )
    # Decimal field for the users height.
    height = DecimalField(
        'height',
        places=2,
        validators=[DataRequired(),NumberRange(min=0,max=3),is_a_float]
    )
    # Decimal field for the users weight.
    weight = DecimalField(
        'weight',
        places=2,
        validators=[DataRequired(),NumberRange(min=0,max=250),is_a_float]
    )
    # Text field for the first line of the users address.
    address_line_1 = TextField(
        'address',
        validators=[DataRequired(),Length(min=5, max=200),is_alpha_numeric]
    )
    # Text field for the users city.
    city = TextField(
        'city',
        validators=[DataRequired(),Length(min=2, max=25),is_alpha_numeric]
    )
    # Text field for the users postcode.
    postcode = TextField(
        'postcode',
        validators=[DataRequired(),Length(min=5,max=9),is_alpha_numeric]
    )

class EditDetailsForm(Form):
    """
    Form for users to edit their personal details. 
    """

     # Text field for the users firstname.
    firstname = TextField(
        'firstname', 
        validators=[DataRequired(),Length(min=2,max=20)]
    )
    # Text field for the users surname.
    surname = TextField(
        'surname', 
        validators=[DataRequired(), Length(min=2,max=20)]
    )
    # Text field for the users email.
    email = TextField(
        'email',
        validators=[DataRequired(),Email(message=None)]
    )
    # Decimal field for the users height.
    height = DecimalField(
        'height',
        places=2,
        validators=[DataRequired(),NumberRange(min=0,max=3)]
    )
    # Text field for the first line of the users address.
    address_line_1 = TextField(
        'address',
        validators=[DataRequired(),Length(min=5, max=200)]
    )
    # Text field for the users city.
    city = TextField(
        'city',
        validators=[DataRequired(),Length(min=2, max=20)]
    )
    # Text field for the users postcode.
    postcode = TextField(
        'postcode',
        validators=[DataRequired(),Length(min=5,max=9)]
    )
    # Password field needed for the user to update their details.
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6,max=32)]
    )

class ChangePasswordForm(Form):
    """
    Form that allows users to change their password.
    """

    # Password field needed for the user to change their password
    current_password = PasswordField(
        'current_password',
        validators=[DataRequired()]
    )
    # Password field for the new password.
    new_password = PasswordField(
        'new_password',
        validators=[DataRequired(), Length(min=6,max=32)]
    )
    # Password field for the new password confirmation.
    new_password_confirm = PasswordField(
        'new_password_confirm',
        validators=[DataRequired(),EqualTo('new_password', message='Passwords must match.')]
    )

traininglog/login/__init__.py
# Required for python to treat directories like packages.

traininglog/login/views.py
# login/views.py
# Jake Malley
# 19/01/15

"""
Define the routes for the login blueprint.
"""

# Imports
from flask import flash, redirect, render_template, request, \
                    url_for, Blueprint
from forms import LoginForm, SignUpForm, EditDetailsForm, ChangePasswordForm
from traininglog import bcrypt, app, db
from traininglog.models import Member,Exercise,Weight,Message
from flask.ext.login import login_user, logout_user, login_required, current_user, fresh_login_required
from datetime import datetime

# Setup the login blueprint.
login_blueprint = Blueprint(
    'login',__name__,
    template_folder='templates'
    )

# Define the routes.
@login_blueprint.route('/login', methods=['GET','POST'])
def login():
    """
    Renders the login_login.html template and displays it the user.
    """

    # If the user is logged in.
    if current_user.is_authenticated():
        # Redirect to the dashboard.
        return redirect(url_for('dashboard.dashboard'))

    # Create an empty error variable.
    error = None

    # If there is anything in the URL args.
    if request.args.get('error'):error = request.args.get('error')

    # Create the login form.
    user_login_form = LoginForm()

    if request.method == 'POST':
        # If the form was submitted. (i.e. data posted to the page.)
        if user_login_form.validate_on_submit():
            # Do the user Login.
            # Query the database for a user that matches the email.
            member = Member.query.filter_by(email=user_login_form.email.data).first()
            if member is not None and bcrypt.check_password_hash(member.password,user_login_form.password.data):
                # The user is valid.
                # Log the In.
                if login_user(member,remember=bool(user_login_form.remember.data)):
                    # All is okay log the user in.
                    flash('Logged In')
                    # Update the last login date.
                    member.set_last_login_date(datetime.utcnow())
                    # Commit changes to the database.
                    db.session.commit()
                    # Due to some errors with old users not having weight data, make sure the user has added weight data.
                    if not member.weight_data:
                        # If no data was found, redirect them to the add page.
                        return redirect(url_for('weight.add_weight',error="You must add a weight to the database before continuing. Otherwise some applications may not work correctly."))

                    # If the user was trying to access a page before he was redirected here
                    # redirect them back to that page.
                    if request.args.get('next') and not request.args.get('next') == "/logout":
                        return redirect(request.args.get('next'))
                    else:
                        # Redirect them to the dashboard page.
                        return redirect(url_for('dashboard.dashboard'))
                else:
                    # The user cannot be logged in.
                    if not member.is_active():
                        # The account is not activated as account_is_active returns False
                        error = "Account is not active, please contact your system administrator."
                    else:
                        # Unknown error.
                        error = "Unknown error occurred, please contact your system administrator."
            else:
                # Either the user does not exist or the password doesn't match.
                # Error message left vague for security.
                error="Invalid Credentials, Please try again."
    
    # Display the login_login.html page to the user.
    return render_template('login_login.html',user_login_form=user_login_form, error=error)

@login_blueprint.route('/signup', methods=['GET','POST'])
def signup():
    """
    Renders the login_signup.html template and displays it to the user.
    """

    # If the user is logged in.
    if current_user.is_authenticated():
        # Redirect to the dashboard.
        return redirect(url_for('dashboard.dashboard'))

    # Create an empty error variable.
    error = None

    # Create the sign up form.
    user_signup_form = SignUpForm()

    if request.method == 'POST':
        if user_signup_form.validate_on_submit():
            # Check the email isn't already in the database.
            member = Member.query.filter_by(email=user_signup_form.email.data).first()
            if member is None:
                # Not in the database, sign up the user.
                # Get the current time.
                now = datetime.utcnow()

                # Try and get the auto_aprove and auto_admin configuration.
                try:
                    if app.config['AUTO_ADMIN']:
                        is_admin = 1
                    else:
                        is_admin = 0
                except KeyError:
                    is_admin = 0

                try:
                    if app.config['AUTO_APPROVE']:
                        is_active = 1
                    else:
                        is_active = 0
                except KeyError:
                    is_active = 0

                member = Member(user_signup_form.firstname.data, user_signup_form.surname.data, user_signup_form.email.data, user_signup_form.password.data, user_signup_form.gender.data, user_signup_form.height.data, user_signup_form.address_line_1.data,user_signup_form.city.data, user_signup_form.postcode.data,now,now,is_admin, is_active)

                db.session.add(member)
                db.session.commit()

                # The ID of the new member.
                new_id = Member.query.filter_by(email=user_signup_form.email.data).first().id
                # Add the users weight to the weight table.
                db.session.add(Weight(user_signup_form.weight.data, now, new_id))

                # Add a welcome message.
                db.session.add(Message(now,"Welcome to the training log! Important messages are displayed here. Click them to delete.", new_id))
                
                # Commit the changes.
                db.session.commit()

                # Redirect them to the dashboard. (Also log them in.)
                if login_user(member):
                    # All is okay log the user in.
                    flash('Logged In')
                    # Redirect them to the dashboard page.
                    return redirect(url_for('dashboard.dashboard'))
                else:
                    # For some reason the user could not be logged in.
                    if not member.is_active():
                        # The account is not activated as account_is_active returns False (AUTO_APPROVE set to False)
                        return redirect(url_for('login.login', error="Before you can login, the system requires an administrator approves your account."))
                    else:
                        # Redirect them to the login page. The error will be dealt with there.
                        return redirect(url_for('login.login'))
            else:
                error = "An account is already associated with this email address."
        else:
            render_template('login_signup.html', user_signup_form=user_signup_form, user_login_form=LoginForm(), error=error)

    # Display the sign up page.
    return render_template('login_signup.html', user_signup_form=user_signup_form, user_login_form=LoginForm(), error=error)

@login_blueprint.route('/logout')
@login_required
def logout():
    """
    Logs the current user out of the application.
    """
    # Logout the current user.
    logout_user()
    # Flash a message to the user.
    flash('You were logged out!')
    # Redirect to the welcome page.
    return redirect(url_for('home.welcome'))

@login_blueprint.route('/myprofile', methods=['GET','POST'])
@fresh_login_required
def myprofile():
    """
    Displays the profile of the current user.
    """

    # Create an empty error variable.
    error = None

    # Create the edit details form.
    user_edit_details_form = EditDetailsForm()

    if request.method == 'POST':
        if user_edit_details_form.validate_on_submit():
            # The form is valid. I.e all the data require is there.
            # Check the password matches the users password.
            if bcrypt.check_password_hash(current_user.password,user_edit_details_form.password.data):
                # Okay that is the correct password make the changes.
                current_user.update_details(user_edit_details_form.firstname.data, user_edit_details_form.surname.data, user_edit_details_form.email.data, user_edit_details_form.height.data, user_edit_details_form.address_line_1.data, user_edit_details_form.city.data, user_edit_details_form.postcode.data)
                # Commit the changes.
                db.session.commit()
                flash("Successfully updated your personal details.")
            else:
                error = "Incorrect Password, changes have not been made."
        else:
            render_template('login_myprofile.html',error=error, user_edit_details_form=user_edit_details_form, user_change_password_form=ChangePasswordForm())
    # Display the my profile to the user.
    return render_template('login_myprofile.html',error=error, user_edit_details_form=user_edit_details_form, user_change_password_form=ChangePasswordForm())

@login_blueprint.route('/chgpasswd', methods=['POST','GET'])
@fresh_login_required
def chgpasswd():
    """
    Changes the users password.

    The only available method is POST as the form is on the 'myprofile' page. This 
    route just validates the form. If the method is GET the user is redirected to the
    'myprofile' page.
    """

    if request.method == 'GET':
        return redirect(request.referrer or url_for('login.myprofile'))

traininglog/login/templates/login.html
<!-- Display login form to the users. -->
{% extends 'layout.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-4 col-md-offset-4" style="text-align:center;padding-top:20px;">
    <div class="text-box">
      <h1>Please Login.</h1>
      <p>A login is required to access the site.</p>
    <form class="form-down" role="form" method="post" action="">
      {{ user_login_form.csrf_token }}

        <!-- If there is an error display it to the user. -->
        {% if error %}
          <p class="alert alert-danger">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              {{ error }}
          </p>
        {% endif %}
        
        {{ user_login_form.email(class="form-control input-top",placeholder="email") }}
        {% for error in user_login_form.email.errors %}
          <p>
          <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
          {{ error }}
          </p>
        {% endfor %}

        {{ user_login_form.password(class="form-control input-bottom",placeholder="password") }}
        {% for error in user_login_form.password.errors %}
          <p>
            <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
            {{ error }}
          </p>
        {% endfor %}
        <p>{{ user_login_form.remember }} Remember Me</p>
        
      <button class="form-control btn btn-sm btn-blue" type="submit">Sign in</button>
    </form>
    </div><!-- .text-box -->
  </div><!-- .col-md-4 col-md-offset-4 -->
</div><!-- .row -->
{% endblock %}

traininglog/login/templates/login_myprofile.html
<!-- Display profile page to the users. -->
{% extends 'dashboard_layout.html' %}
{% block title %}{{ current_user.get_full_name()}}{% endblock %}
{%block breadcrumb %}
<li><a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a></li>
<li class="active">{{current_user.get_firstname()}}'s Profile</li>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2" style="padding-top:20px;">
        <div class="text-box">

            <!-- Personal Details -->
            <div id="personal-details" class="page-header">
                <h1>{{current_user.get_firstname()}}'s Profile<br/>
                <small>Personal Details</small></h1>
            </div>

            <!-- If there is an error display it to the user. -->
            {% if error %}
                <p class="alert alert-danger">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    {{ error }}
                </p>
            {% endif %}

            <table class="table table-hover" style="text-align:left;">
                <tr>
                    <th>Firstname</th>
                    <th>Surname</th>
                </tr>
                <tr>
                    <td>{{current_user.get_firstname()}}</td>
                    <td>{{current_user.get_surname()}}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <th>Gender</th>
                </tr>
                <tr>
                    <td>{{current_user.get_email()}}</td>
                    <td>{{current_user.get_gender()}}</td>
                </tr>
                <tr>
                    <th>Height</th>
                    <th>Current Weight</th>
                </tr>
                <tr>
                    <td>{{current_user.get_height()}} Meters</td>
                    <td>{% if current_user.weight_data %}{{current_user.weight_data[-1].weight}} Kilograms{% else %}No weight data could be found.{%endif %}</td>
                </tr>
                <tr>
                    <th>Address</th>
                    <th></th>
                </tr>
                <tr>
                    <td>{{current_user.get_address()}}</td>
                    <td></td>
                </tr>
                <tr>
                    <th>Join Date</th>
                    <th>Last Login Date</th>
                </tr>
                <tr>
                    <td>{{current_user.get_join_date()}}</td>
                    <td>{{current_user.get_last_login_date()}}</td>
                </tr>
                <tr>
                    <th>Administrator</th>
                    <th></th>
                </tr>
                <tr>
                    <td>{% if current_user.is_administrator() %}Yes{% else %}No{% endif %}</td>
                    <td></td>
                </tr>
            </table>

            <!-- Errors from the editDetailsForm in the Modal. -->
            {% for field, errors in user_edit_details_form.errors.items() %}
                <p><span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                The {{ field }} field had the following error: {{ errors[0] }}</p>
            {% endfor %}

            <!-- Button trigger modal -->
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#editDetailsModal">
              Edit Personal Details
            </button>

            <!-- editDetailsModal -->
            <div class="modal fade" id="editDetailsModal" tabindex="-1" role="dialog" aria-labelledby="Edit Personal Details" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Edit Personal Details</h4>
                        </div>
                        <div class="modal-body">
                            <form id="editDetailsForm" class="form-down" role="form" method="post" action="{{ url_for('login.myprofile')}}">
                                {{ user_edit_details_form.csrf_token }}
                                <p>
                                Please amend your personal details and click 'save changes' when done.
                                </p>
                                <p>
                                    {{ user_edit_details_form.firstname(class="form-control",value=current_user.get_firstname()) }}
                                </p>
                                <p>
                                    {{ user_edit_details_form.surname(class="form-control",value=current_user.get_surname()) }}
                                </p>
                                <p>
                                    {{ user_edit_details_form.email(class="form-control",value=current_user.get_email()) }}
                                </p>
                                <p>
                                    {{ user_edit_details_form.height(class="form-control",value=current_user.get_height()) }}
                                </p>
                                <p>
                                    {{ user_edit_details_form.address_line_1(class="form-control",value=current_user.address_line_1) }}
                                </p>
                                <p>
                                    {{ user_edit_details_form.city(class="form-control",value=current_user.city) }}
                                </p>
                                <p>
                                    {{ user_edit_details_form.postcode(class="form-control",value=current_user.postcode) }}
                                </p>
                                    <div class="alert alert-danger" role="alert">
                                        Please enter your current password to authorise these changes.
                                    </div>
                                <p>
                                    {{ user_edit_details_form.password(class="form-control",placeholder="Password") }}
                                </p>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button class="btn btn-blue" type="submit" onclick=" $('#editDetailsForm').submit();">Save Changes</button>
                        </div>
                    </div>
                </div>
            </div><!-- editDetailsModal -->

            <!-- Change Password -->
            <div id="change-password" class="page-header">
                <h1><small>Change Password</small></h1>
            </div>
            <form role="form" method="post" action="{{ url_for('login.chgpasswd')}}">
                {{ user_change_password_form.csrf_token }}

                <div class="form-group">
                {{ user_change_password_form.current_password(class="form-control",placeholder="Current Password") }}
                    {% for error in user_change_password_form.current_password.errors %}
                        <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                        {{ error }}
                    {% endfor %}
                </div>

                <div class="form-group">
                {{ user_change_password_form.new_password(class="form-control",placeholder="New Password") }}
                    {% for error in user_change_password_form.new_password.errors %}
                        <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                        {{ error }}
                    {% endfor %}
                </div>

                <div class="form-group">
                {{ user_change_password_form.new_password_confirm(class="form-control",placeholder="Confirm New Password") }}
                    {% for error in user_change_password_form.new_password_confirm.errors %}
                        <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                        {{ error }}
                    {% endfor %}
                </div>

                <button class="btn btn-blue" type="submit" onclick=" $('#editDetailsForm').submit();">Change Password</button>
                </form>

                <!-- Delete/Deactivate Account -->
                <div id="account-settings" class="page-header">
                    <h1><small>Account Settings</small></h1>
                </div>
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                    <strong>Danger Zone!</strong> These actions cannot be undone.
                </div>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deactivateAccountModal">Deactivate Your Account.</button>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteAccountModal">Delete Your Account.</button>

                <!-- Modal for deactivating your account. -->
                <div class="modal fade" id="deactivateAccountModal" tabindex="-1" role="dialog" aria-labelledby="Deactivate Account?" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Deactivate Account.</h4>
                        </div>
                        <div class="modal-body">
                            <div class="alert alert-danger" role="alert">
                                <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                                Are you sure you want to deactivate your account? You will not be able to run in the charity event. <strong>This action cannot be undone!</strong>
                            </div>
                            <form class="form-inline" id="deactivateAccountForm" method="POST" action="{{ url_for('login.deactivate_account') }}">
                                <input type="hidden" name="deactivate_account" value="True">
                                <label for="password">Enter your Password:</label>
                                <input class="form-control" type="password" name="password" placeholder="password">
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button class="btn btn-danger" type="submit" onclick=" $('#deactivateAccountForm').submit();">Deactivate Account</button>
                        </div>
                    </div>
                </div>
            </div><!-- deactivateAccountModal -->

            <!-- Modal for deleting your account. -->
                <div class="modal fade" id="deleteAccountModal" tabindex="-1" role="dialog" aria-labelledby="Delete Account?" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Delete Account.</h4>
                        </div>
                        <div class="modal-body">
                            <div class="alert alert-danger" role="alert">
                                <span class="glyphicon glyphicon-exclamation-sign" style="color:#bb321f;" aria-hidden="true"></span>
                                Are you sure you want to delete your account? All of your exercise data will be removed and you will not be able to run in the charity event. <strong>This action cannot be undone!</strong>
                            </div>
                            <form class="form-inline" id="deleteAccountForm" method="POST" action="{{ url_for('login.delete_account') }}">
                                <input type="hidden" name="delete_account" value="True">
                                <label for="password">Enter your Password:</label>
                                <input class="form-control" type="password" name="password" placeholder="password">
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button class="btn btn-danger" type="submit" onclick=" $('#deleteAccountForm').submit();">Delete Account</button>
                        </div>
                    </div>
                </div>
            </div><!-- deactivateAccountModal -->

        </div>
    </div><!-- .col-md-8 col-md-offset-2 -->
</div><!-- .row -->
{% endblock %}